# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('answer_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('question_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.ManyToManyField(to='qna.Answer')),
                ('question_name', models.ManyToManyField(to='qna.Question')),
                ('upvoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_name', to='qna.Question'),
        ),
    ]
