# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='answer_name',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='question_name',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
