# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-23 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0002_auto_20171122_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('upvoted_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_answer', to='qna.Answer')),
                ('upvoted_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='upvote',
            name='upvoted_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_question', to='qna.Question'),
        ),
    ]
